import '../models/learning_lesson_model.dart';

class LearningRepository {
  static const List<LearningLessonModel> allLessons = [
    // ══════════════════════════════════════════════════════════════
    // CATEGORY 1: DAILY DHIKR
    // ══════════════════════════════════════════════════════════════
    LearningLessonModel(
      id: 'dhikr_subhanallah',
      category: LearningCategory.dailyDhikr,
      title: 'Tasbih (SubhanAllah)',
      arabicText: 'سُبْحَانَ اللَّهِ',
      transliteration: 'Subḥān Allāh',
      translation: 'Glory be to Allah, free is He from all imperfections.',
      sourceReference: 'Sahih Muslim 2691',
      minRecitationSeconds: 3,
      targetRepetitions: 33,
    ),
    LearningLessonModel(
      id: 'dhikr_alhamdulillah',
      category: LearningCategory.dailyDhikr,
      title: 'Tahmid (Alhamdulillah)',
      arabicText: 'الْحَمْدُ لِلَّهِ',
      transliteration: 'Al-ḥamdu lillāh',
      translation: 'All praise and gratitude belong to Allah alone.',
      sourceReference: 'Sahih Muslim 223',
      minRecitationSeconds: 3,
      targetRepetitions: 33,
    ),
    LearningLessonModel(
      id: 'dhikr_allahuakbar',
      category: LearningCategory.dailyDhikr,
      title: 'Takbir (Allahu Akbar)',
      arabicText: 'اللَّهُ أَكْبَرُ',
      transliteration: 'Allāhu Akbar',
      translation: 'Allah is the Greatest, above all in majesty.',
      sourceReference: 'Sahih al-Bukhari 6329',
      minRecitationSeconds: 3,
      targetRepetitions: 34,
    ),
    LearningLessonModel(
      id: 'dhikr_astaghfirullah',
      category: LearningCategory.dailyDhikr,
      title: 'Istighfar (Astaghfirullah)',
      arabicText: 'أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ',
      transliteration: 'Astaghfirullāha wa atūbu ilayh',
      translation: 'I seek the forgiveness of Allah and I turn to Him in repentance.',
      sourceReference: 'Sahih al-Bukhari 6307',
      minRecitationSeconds: 4,
      targetRepetitions: 100,
    ),
    LearningLessonModel(
      id: 'dhikr_salawat',
      category: LearningCategory.dailyDhikr,
      title: 'Salawat upon the Prophet ﷺ',
      arabicText: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ',
      transliteration: 'Allāhumma ṣalli ‘alā Muḥammadin wa ‘alā āli Muḥammad',
      translation: 'O Allah, bestow peace and blessings upon Muhammad and the family of Muhammad.',
      sourceReference: 'Sahih al-Bukhari 3370',
      minRecitationSeconds: 4,
      targetRepetitions: 10,
    ),

    // ══════════════════════════════════════════════════════════════
    // CATEGORY 2: DAILY DUAS
    // ══════════════════════════════════════════════════════════════
    LearningLessonModel(
      id: 'dua_before_eating',
      category: LearningCategory.dailyDuas,
      title: 'Dua Before Eating',
      arabicText: 'بِسْمِ اللَّهِ',
      transliteration: 'Bismillāh',
      translation: 'In the name of Allah.',
      sourceReference: 'Sahih al-Bukhari 5376',
      minRecitationSeconds: 2,
    ),
    LearningLessonModel(
      id: 'dua_after_eating',
      category: LearningCategory.dailyDuas,
      title: 'Dua After Eating',
      arabicText: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ',
      transliteration: 'Al-ḥamdu lillāhilladhī aṭ‘amanī hādhā wa razaqanīhi min ghayri ḥawlin minnī wa lā quwwah',
      translation: 'Praise belongs to Allah Who has fed me this and provided it for me without any strength or power on my part.',
      sourceReference: 'Sunan Abi Dawud 4023 (Sahih by Al-Albani)',
      minRecitationSeconds: 6,
    ),
    LearningLessonModel(
      id: 'dua_before_sleeping',
      category: LearningCategory.dailyDuas,
      title: 'Dua Before Sleeping',
      arabicText: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
      transliteration: 'Bismika Allāhumma amūtu wa aḥyā',
      translation: 'In Your name, O Allah, I die and I live.',
      sourceReference: 'Sahih al-Bukhari 6312',
      minRecitationSeconds: 3,
    ),
    LearningLessonModel(
      id: 'dua_after_waking',
      category: LearningCategory.dailyDuas,
      title: 'Dua Upon Waking Up',
      arabicText: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
      transliteration: 'Al-ḥamdu lillāhilladhī aḥyānā ba‘da mā amātanā wa ilayhin-nushūr',
      translation: 'Praise be to Allah Who brought us to life after having caused us to die, and unto Him is the resurrection.',
      sourceReference: 'Sahih al-Bukhari 6312',
      minRecitationSeconds: 5,
    ),
    LearningLessonModel(
      id: 'dua_entering_home',
      category: LearningCategory.dailyDuas,
      title: 'Dua Entering Home',
      arabicText: 'بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَى رَبِّنَا تَوَكَّلْنَا',
      transliteration: 'Bismillāhi walajnā, wa bismillāhi kharajnā, wa ‘alā rabbinā tawakkalnā',
      translation: 'In the name of Allah we enter, and in the name of Allah we leave, and upon our Lord we rely.',
      sourceReference: 'Sunan Abi Dawud 5096',
      minRecitationSeconds: 5,
    ),
    LearningLessonModel(
      id: 'dua_leaving_home',
      category: LearningCategory.dailyDuas,
      title: 'Dua Leaving Home',
      arabicText: 'بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
      transliteration: 'Bismillāhi, tawakkaltu ‘alallāh, wa lā ḥawla wa lā quwwata illā billāh',
      translation: 'In the name of Allah, I trust in Allah; there is no might and no power except with Allah.',
      sourceReference: 'Sunan Abi Dawud 5095 (Sahih)',
      minRecitationSeconds: 5,
    ),
    LearningLessonModel(
      id: 'dua_entering_mosque',
      category: LearningCategory.dailyDuas,
      title: 'Dua Entering the Mosque',
      arabicText: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
      transliteration: 'Allāhummaf-taḥ lī abwāba raḥmatik',
      translation: 'O Allah, open for me the gates of Your mercy.',
      sourceReference: 'Sahih Muslim 713',
      minRecitationSeconds: 3,
    ),
    LearningLessonModel(
      id: 'dua_leaving_mosque',
      category: LearningCategory.dailyDuas,
      title: 'Dua Leaving the Mosque',
      arabicText: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
      transliteration: 'Allāhumma innī as’aluka min faḍlik',
      translation: 'O Allah, I ask You from Your bounty.',
      sourceReference: 'Sahih Muslim 713',
      minRecitationSeconds: 3,
    ),

    // ══════════════════════════════════════════════════════════════
    // CATEGORY 3: SALAH LEARNING
    // ══════════════════════════════════════════════════════════════
    LearningLessonModel(
      id: 'salah_takbir',
      category: LearningCategory.salahLearning,
      title: 'Takbiratul Ihram (Opening)',
      arabicText: 'اللَّهُ أَكْبَرُ',
      transliteration: 'Allāhu Akbar',
      translation: 'Allah is the Greatest.',
      sourceReference: 'Sahih al-Bukhari 735',
      minRecitationSeconds: 2,
    ),
    LearningLessonModel(
      id: 'salah_sana',
      category: LearningCategory.salahLearning,
      title: 'Sana (Opening Supplication)',
      arabicText: 'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، وَتَبَارَكَ اسْمُكَ، وَتَعَالَى جَدُّكَ، وَلَا إِلَهَ غَيْرُكَ',
      transliteration: 'Subḥānakallāhumma wa biḥamdika, wa tabārakasmuka, wa ta‘ālā jadduka, wa lā ilāha ghayruk',
      translation: 'Glory be to You, O Allah, and all praise. Blessed is Your name, exalted is Your majesty, and there is no deity worthy of worship besides You.',
      sourceReference: 'Sunan an-Nasa’i 899 (Sahih)',
      minRecitationSeconds: 6,
    ),
    LearningLessonModel(
      id: 'salah_fatihah',
      category: LearningCategory.salahLearning,
      title: 'Surah Al-Fatihah (The Opening)',
      arabicText: 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ • الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ • الرَّحْمَنِ الرَّحِيمِ • مَالِكِ يَوْمِ الدِّينِ • إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ • اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ • صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',
      transliteration: 'Bismillāhir-Raḥmānir-Raḥīm. Al-ḥamdu lillāhi Rabbil-‘ālamīn. Ar-Raḥmānir-Raḥīm. Māliki yawmid-dīn. Iyyāka na‘budu wa iyyāka nasta‘īn. Ihdinaṣ-ṣirāṭal-mustaqīm. Ṣirāṭalladhīna an‘amta ‘alayhim ghayril-maghḍūbi ‘alayhim wa laḍ-ḍāllīn.',
      translation: 'In the name of Allah, Most Gracious, Most Merciful. All praise is due to Allah, Lord of the worlds. The Most Gracious, the Most Merciful. Master of the Day of Judgment. You alone we worship and You alone we ask for help. Guide us to the straight path: the path of those whom You have blessed, not of those who have evoked Your anger or of those who are astray.',
      sourceReference: 'Quran 1:1-7',
      minRecitationSeconds: 12,
    ),
    LearningLessonModel(
      id: 'salah_ruku',
      category: LearningCategory.salahLearning,
      title: 'Dhikr in Ruku (Bowing)',
      arabicText: 'سُبْحَانَ رَبِّيَ الْعَظِيمِ',
      transliteration: 'Subḥāna Rabbiyal-‘Aẓīm',
      translation: 'Glory be to my Lord, the Most Magnificent.',
      sourceReference: 'Sahih Muslim 772',
      minRecitationSeconds: 3,
      targetRepetitions: 3,
    ),
    LearningLessonModel(
      id: 'salah_sujood',
      category: LearningCategory.salahLearning,
      title: 'Dhikr in Sujood (Prostration)',
      arabicText: 'سُبْحَانَ رَبِّيَ الْأَعْلَى',
      transliteration: 'Subḥāna Rabbiyal-A‘lā',
      translation: 'Glory be to my Lord, the Most High.',
      sourceReference: 'Sahih Muslim 772',
      minRecitationSeconds: 3,
      targetRepetitions: 3,
    ),
    LearningLessonModel(
      id: 'salah_tashahhud',
      category: LearningCategory.salahLearning,
      title: 'At-Tashahhud',
      arabicText: 'التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ',
      transliteration: 'At-taḥiyyātu lillāhi waṣ-ṣalawātu waṭ-ṭayyibāt. As-salāmu ‘alayka ayyuhan-Nabiyyu wa raḥmatullāhi wa barakātuh. As-salāmu ‘alaynā wa ‘alā ‘ibādillāhiṣ-ṣāliḥīn. Ash-hadu allā ilāha illallāhu wa ash-hadu anna Muḥammadan ‘abduhū wa rasūluh.',
      translation: 'All compliments, prayers and pure words are due to Allah. Peace be upon you, O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous servants of Allah. I bear witness that none has the right to be worshipped except Allah, and I bear witness that Muhammad is His servant and messenger.',
      sourceReference: 'Sahih al-Bukhari 1202',
      minRecitationSeconds: 8,
    ),
    LearningLessonModel(
      id: 'salah_durood',
      category: LearningCategory.salahLearning,
      title: 'Durood Ibrahimiyyah',
      arabicText: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ',
      transliteration: 'Allāhumma ṣalli ‘alā Muḥammadin wa ‘alā āli Muḥammad, kamā ṣallayta ‘alā Ibrāhīma wa ‘alā āli Ibrāhīm, innaka Ḥamīdun Majīd. Allāhumma bārik ‘alā Muḥammadin wa ‘alā āli Muḥammad, kamā bārakta ‘alā Ibrāhīma wa ‘alā āli Ibrāhīm, innaka Ḥamīdun Majīd.',
      translation: 'O Allah, send prayers upon Muhammad and upon the family of Muhammad, as You sent prayers upon Ibrahim and the family of Ibrahim; indeed, You are Praiseworthy and Glorious. O Allah, send blessings upon Muhammad and upon the family of Muhammad, as You sent blessings upon Ibrahim and the family of Ibrahim; indeed, You are Praiseworthy and Glorious.',
      sourceReference: 'Sahih al-Bukhari 3370',
      minRecitationSeconds: 10,
    ),
    LearningLessonModel(
      id: 'salah_dua_after',
      category: LearningCategory.salahLearning,
      title: 'Dua After Taslim',
      arabicText: 'اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ',
      transliteration: 'Allāhumma Antas-Salāmu wa minkas-salām, tabārakta yā Dhal-Jalāli wal-Ikrām',
      translation: 'O Allah, You are Peace and from You comes peace. Blessed are You, O Owner of majesty and honor.',
      sourceReference: 'Sahih Muslim 592',
      minRecitationSeconds: 4,
    ),

    // ══════════════════════════════════════════════════════════════
    // CATEGORY 4: SHORT SURAHS
    // ══════════════════════════════════════════════════════════════
    LearningLessonModel(
      id: 'surah_ikhlas',
      category: LearningCategory.shortSurahs,
      title: 'Surah Al-Ikhlas (Purity of Faith)',
      arabicText: 'قُلْ هُوَ اللَّهُ أَحَدٌ • اللَّهُ الصَّمَدُ • لَمْ يَلِدْ وَلَمْ يُولَدْ • وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ',
      transliteration: 'Qul Huwallāhu Aḥad. Allāhuṣ-Ṣamad. Lam yalid wa lam yūlad. Wa lam yakun lahū kufuwan aḥad.',
      translation: 'Say, He is Allah, [who is] One. Allah, the Eternal Refuge. He neither begets nor is born. Nor is there to Him any equivalent.',
      sourceReference: 'Quran 112:1-4',
      minRecitationSeconds: 5,
    ),
    LearningLessonModel(
      id: 'surah_falaq',
      category: LearningCategory.shortSurahs,
      title: 'Surah Al-Falaq (The Daybreak)',
      arabicText: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ • مِنْ شَرِّ مَا خَلَقَ • وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ • وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ • وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ',
      transliteration: 'Qul a‘ūdhu bi-Rabbil-falaq. Min sharri mā khalaq. Wa min sharri ghāsiqin idhā waqab. Wa min sharrin-naffāthāti fil-‘uqad. Wa min sharri ḥāsidin idhā ḥasad.',
      translation: 'Say, I seek refuge in the Lord of daybreak. From the evil of that which He created. And from the evil of darkness when it settles. And from the evil of the blowers in knots. And from the evil of an envier when he envies.',
      sourceReference: 'Quran 113:1-5',
      minRecitationSeconds: 7,
    ),
    LearningLessonModel(
      id: 'surah_nas',
      category: LearningCategory.shortSurahs,
      title: 'Surah An-Nas (Mankind)',
      arabicText: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ • مَلِكِ النَّاسِ • إِلَهِ النَّاسِ • مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ • الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ • مِنَ الْجِنَّةِ وَالنَّاسِ',
      transliteration: 'Qul a‘ūdhu bi-Rabbin-nās. Malikin-nās. Ilāhin-nās. Min sharril-waswāsil-khannās. Alladhī yuwaswisu fī ṣudūrin-nās. Minal-jinnati wan-nās.',
      translation: 'Say, I seek refuge in the Lord of mankind. The Sovereign of mankind. The God of mankind. From the evil of the retreating whisperer — who whispers into the breasts of mankind — from among the jinn and mankind.',
      sourceReference: 'Quran 114:1-6',
      minRecitationSeconds: 8,
    ),
    LearningLessonModel(
      id: 'surah_kawthar',
      category: LearningCategory.shortSurahs,
      title: 'Surah Al-Kawthar (Abundance)',
      arabicText: 'إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ • فَصَلِّ لِرَبِّكَ وَانْحَرْ • إِنَّ شَانِئَكَ هُوَ الْأَبْتَرُ',
      transliteration: 'Innā a‘ṭaynākal-kawthar. Faṣalli li-Rabbika wanḥar. Inna shāni’aka huwal-abtar.',
      translation: 'Indeed, We have granted you, [O Muhammad], al-Kawthar. So pray to your Lord and sacrifice. Indeed, your enemy is the one cut off.',
      sourceReference: 'Quran 108:1-3',
      minRecitationSeconds: 5,
    ),
    LearningLessonModel(
      id: 'surah_asr',
      category: LearningCategory.shortSurahs,
      title: 'Surah Al-Asr (The Declining Day)',
      arabicText: 'وَالْعَصْرِ • إِنَّ الْإِنْسَانَ لَفِي خُسْرٍ • إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ',
      transliteration: 'Wal-‘aṣr. Innal-insāna lafī khusr. Illalladhīna āmanū wa ‘amiluṣ-ṣāliḥāti wa tawāṣaw bil-ḥaqqi wa tawāṣaw biṣ-ṣabr.',
      translation: 'By time, indeed, mankind is in loss, except for those who have believed and done righteous deeds and advised each other to truth and advised each other to patience.',
      sourceReference: 'Quran 103:1-3',
      minRecitationSeconds: 6,
    ),
    LearningLessonModel(
      id: 'surah_nasr',
      category: LearningCategory.shortSurahs,
      title: 'Surah An-Nasr (The Divine Help)',
      arabicText: 'إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ • وَرَأَيْتَ النَّاسَ يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا • فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ إِنَّهُ كَانَ تَوَّابًا',
      transliteration: 'Idhā jā’a naṣrullāhi wal-fatḥ. Wa ra’aytan-nāsa yadkhulūna fī dīnillāhi afwājā. Fa-sabbiḥ bi-ḥamdi Rabbika wastaghfirh, innahū kāna Tawwābā.',
      translation: 'When the victory of Allah has come and the conquest, and you see the people entering into the religion of Allah in multitudes, then exalt [Him] with praise of your Lord and ask forgiveness of Him. Indeed, He is ever Accepting of repentance.',
      sourceReference: 'Quran 110:1-3',
      minRecitationSeconds: 7,
    ),
    LearningLessonModel(
      id: 'surah_kafirun',
      category: LearningCategory.shortSurahs,
      title: 'Surah Al-Kafirun (The Disbelievers)',
      arabicText: 'قُلْ يَا أَيُّهَا الْكَافِرُونَ • لَا أَعْبُدُ مَا تَعْبُدُونَ • وَلَا أَنْتُمْ عَابِدُونَ مَا أَعْبُدُ • وَلَا أَنَا عَابِدٌ مَا عَبَدْتُّمْ • وَلَا أَنْتُمْ عَابِدُونَ مَا أَعْبُدُ • لَكُمْ دِينُكُمْ وَلِيَ دِينِ',
      transliteration: 'Qul yā ayyuhal-kāfirūn. Lā a‘budu mā ta‘budūn. Wa lā antum ‘ābidūna mā a‘bud. Wa lā ana ‘ābidum-mā ‘abattum. Wa lā antum ‘ābidūna mā a‘bud. Lakum dīnukum wa liya dīn.',
      translation: 'Say, O disbelievers, I do not worship what you worship. Nor are you worshippers of what I worship. Nor will I be a worshipper of what you worship. Nor will you be worshippers of what I worship. For you is your religion, and for me is my religion.',
      sourceReference: 'Quran 109:1-6',
      minRecitationSeconds: 8,
    ),
  ];
}
