// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY_aAxw7cAZippBsTlyb7fSuzxBzR1sbQ',
    appId: '1:422731970610:web:842803442ed762e551242b',
    messagingSenderId: '422731970610',
    projectId: 'focusdeen-f8295',
    authDomain: 'focusdeen-f8295.firebaseapp.com',
    storageBucket: 'focusdeen-f8295.firebasestorage.app',
    databaseURL: 'https://focusdeen-f8295-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1YjlhtWrJIrc2yG0eM3v5g-3Q_N17uxg',
    appId: '1:422731970610:android:89acc8d98969405851242b',
    messagingSenderId: '422731970610',
    projectId: 'focusdeen-f8295',
    storageBucket: 'focusdeen-f8295.firebasestorage.app',
    databaseURL: 'https://focusdeen-f8295-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoxMH4mAn04Oy_F2Yc6ZtHejkB7MmP6e8',
    appId: '1:422731970610:ios:95a76790e657a29d51242b',
    messagingSenderId: '422731970610',
    projectId: 'focusdeen-f8295',
    storageBucket: 'focusdeen-f8295.firebasestorage.app',
    iosBundleId: 'com.focusdeen.focusDeen',
    databaseURL: 'https://focusdeen-f8295-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoxMH4mAn04Oy_F2Yc6ZtHejkB7MmP6e8',
    appId: '1:422731970610:ios:95a76790e657a29d51242b',
    messagingSenderId: '422731970610',
    projectId: 'focusdeen-f8295',
    storageBucket: 'focusdeen-f8295.firebasestorage.app',
    iosBundleId: 'com.focusdeen.focusDeen',
    databaseURL: 'https://focusdeen-f8295-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY_aAxw7cAZippBsTlyb7fSuzxBzR1sbQ',
    appId: '1:422731970610:web:ef43a111c4aa865f51242b',
    messagingSenderId: '422731970610',
    projectId: 'focusdeen-f8295',
    authDomain: 'focusdeen-f8295.firebaseapp.com',
    storageBucket: 'focusdeen-f8295.firebasestorage.app',
    databaseURL: 'https://focusdeen-f8295-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
